name: getGR

on:
  schedule:
    - cron: '30 17 * * *'  # Runs at 17:30 UTC, which is 11:00 PM IST

  # push:
  #   branches: [ main ]

jobs:
  upload_to_archive:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.16"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'


      - name: Install dependencies
        run: make install

      - name: Upload to archive
        env:
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}

        run: make upload_all_to_archive

      - name: Pull changes in the repository
        run: |
          git pull

      - name: Commit and Push Changes
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Uploaded to archive


